---

  - name: Put Foreman SELinux into permissive
    selinux:
      policy: targeted
      state: permissive
    when: install_foreman|bool

  - name: Install Katello Nightly RPM
    yum:
      name: https://fedorapeople.org/groups/katello/releases/yum/nightly/katello/el7/x86_64/katello-repos-latest.rpm
      state: present
      validate_certs: no
    when: install_foreman|bool

  - name: Install Foreman Nightly RPM
    yum:
      name: https://yum.theforeman.org/releases/nightly/el7/x86_64/foreman-release.rpm
      state: present
      validate_certs: no
    when: install_foreman|bool
  
  - name: Install Puppet repo
    yum:
      name: https://yum.puppet.com/puppet6-release-el-7.noarch.rpm
      state: present
      validate_certs: no
    when: install_foreman|bool

  - name: Install EPEL
    yum:
      name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
      state: present
      validate_certs: no
    when: install_foreman|bool

  - name: Install Foreman SCL
    yum:
      name: foreman-release-scl
      state: present
    when: install_foreman|bool

  - name: Install Katello
    yum:
      name: katello
      state: present
    when: install_foreman|bool

  - name: Install Foreman VMware Compute Resource
    yum:
      name: foreman-vmware
      state: present
    when: install_foreman|bool

  - name: Install Foreman Bootdisk Plugin
    yum:
      name: tfm-rubygem-foreman_bootdisk*
      state: present
    when: install_foreman|bool

  - name: Update OS packages
    yum:
      name: '*'
      state: latest
    when: install_foreman|bool

  - name: Turn off Firewall
    service:
      name: firewalld
      state: stopped
      enabled: no
    when: install_foreman|bool

  - name: Download Configs to drop in for installer
    get_url:
      url: http://10.8.105.2/pub/config_files.tar.gz
      dest: /root/config_files.tar.gz
      force: yes
    when: install_foreman|bool

  - name: Untar config_files and place in /etc
    command: tar --overwrite -xvf /root/config_files.tar.gz -C /
    args:
      warn: no
    register: untar
    when: install_foreman|bool

  - name: Download PostgresDB
    get_url:
      url: http://10.8.105.2/pub/pgsql_data.tar.gz
      dest: /root/pgsql_data.tar.gz
      force: yes
    when: install_foreman|bool

  - name: Download MongoDB
    get_url:
      url: http://10.8.105.2/pub/mongo_data.tar.gz
      dest: /root/mongo_data.tar.gz
      force: yes
    when: install_foreman|bool

  - name: Extract MongoDB
    command: tar --overwrite -xvf /root/mongo_data.tar.gz -C /
    args:
      warn: no
    register: untar
    when: install_foreman|bool

  - name: Extract PostgresDB
    command: tar --overwrite -xvf /root/pgsql_data.tar.gz -C /
    args:
      warn: no
    register: untar
    when: install_foreman|bool

  - name: Install Katello to get slate good
    command: foreman-installer --scenario katello -v -s --disable-system-checks
    register: install
    when: install_foreman|bool

  - name: Perform upgrade with Installer to prevent any issues with the databases
    command: foreman-installer --scenario katello -v -s --disable-system-checks --upgrade
    register: upgrade
    when: install_foreman|bool

  - name: Clean up root directory of backups
    file:
      path: "/root/{{ item }}"
      state: absent
    with_items:
      - mongo_data.tar.gz
      - pgsql_data.tar.gz
      - config_files.tar.gz
    when: install_foreman|bool