---

  - name: Power on VMware VM
    vmware_guest_powerstate:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      folder: "/{{ vcenter_datacenter }}/{{ vcenter_folder }}"
      name: "{{ vcenter_vm_name }}"
      state: powered-on
    delegate_to: localhost

  - name: Wait two minutes for VM to be online
    wait_for: timeout=120
    delegate_to: localhost

  - name: Install Foreman Nightly
    import_tasks: tasks/install.yml
    when: install_foreman|bool

  - name: Upgrade Foreman Nightly
    import_tasks: tasks/upgrade.yml
    when: update_foreman|bool

  - name: Install Satellite latest snap
    import_tasks: tasks/sat-install.yml
    when: (when sat_install|bool)

  - name: Upgrade Satellite latest snap
    import_tasks: tasks/sat-upgrade.yml
    when: (when sat_upgrade|bool)

  - name: Delete VMS before reverting snapshot to prevent name taken error
    import_tasks: remove-hosts.yml
    static: yes
    ignore_errors: yes

  - name: Downloading fog-vsphere patch for testing
    get_url:
      dest: /root/fog.patch
      url: "{{ fogpatch_url }}"
    when: test_pr|bool

  - name: Appling /root/fog.patch to fog-vsphere for testing
    patch:
      src: /root/fog.patch
      remote_src: yes
      strip: 1
      basedir: /opt/theforeman/tfm/root/usr/share/gems/gems/{{ fog_version }}/
    when: test_pr|bool

  - name: Create fog-testing directory in root
    file:
      path: /root/fog-testing
      state: directory
      mode: 0755

  - name: Download requested version of fog-vsphere
    get_url:
      dest: /root/v{{ test_fog_version }}.tar.gz
      force: yes
      url: https://github.com/fog/fog-vsphere/archive/v{{ test_fog_version }}.tar.gz
    when: override_fog|bool

  - name: Extract fog-vsphere archive into gem directory
    unarchive:
      dest: /opt/theforeman/tfm/root/usr/share/gems/gems/{{ fog_version }}
      extra_opts:
        - --overwrite
      src: /root/v{{ test_fog_version }}.tar.gz
    when: override_fog|bool

  - name: Replace hammer config for root user to prevent timeout issues
    copy:
      src: "{{ role_path }}/files/foreman.yml"
      dest: /root/.hammer/cli.modules.d/foreman.yml

  - name: Start regression testing defined in create-hosts.yml
    block:
      - import_tasks: create-hosts.yml
    rescue:
      - debug:
          msg: An error occurred during the testing,rolling back to snapshot.
        when: is_debug is defined|bool
      - import_tasks: remove-hosts.yml
        static: yes

  - name: Delete VMS before reverting snapshot to prevent name taken error
    import_tasks: remove-hosts.yml
    static: yes

  - name: Poweroff Foreman Nightly VM
    vmware_guest_powerstate:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      folder: "/{{ vcenter_datacenter }}/{{ vcenter_folder }}"
      name: "{{ vcenter_vm_name }}"
      state: powered-off
    delegate_to: localhost
