---
# 567 seconds from vm creation to reboot for PXE/Bootdisk

  - name: Poweron Foreman Nightly VM
    vmware_guest_powerstate:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      folder: "/{{ vcenter_datacenter }}/{{ vcenter_folder }}"
      name: "{{ vcenter_vm_name }}"
      state: powered-on
    delegate_to: localhost

  - name: Install Foreman Nightly
    import_tasks: tasks/install.yml
    when: install_foreman|bool

  - name: Put Foreman SELinux into permissive
    selinux:
      policy: targeted
      state: permissive

  - name: Downloading fog-vsphere patch for testing
    get_url:
      dest: /root/fog.patch
      url: "{{ fogpatch_url }}"
    when: test_pr|bool

  - name: Appling /root/fog.patch to fog-vsphere for testing
    patch:
      src: /root/fog.patch
      remote_src: yes
      strip: 1
      basedir: /opt/theforeman/tfm/root/usr/share/gems/gems/{{ fog_version }}/
    when: test_pr|bool

  - name: Create fog-testing directory in root
    file:
      path: /root/fog-testing
      state: directory
      mode: 0755

  - name: Download requested version of fog-vsphere
    get_url:
      dest: /root/v{{ test_fog_version }}.tar.gz
      force: yes
      url: https://github.com/fog/fog-vsphere/archive/v{{ test_fog_version }}.tar.gz
    when: override_fog|bool

  - name: Extract fog-vsphere archive into gem directory
    unarchive:
      dest: /opt/theforeman/tfm/root/usr/share/gems/gems/{{ fog_version }}
      extra_opts:
        - --overwrite
      src: /root/v{{ test_fog_version }}.tar.gz
    when: override_fog|bool

  - name: Restart Katello/Foreman services
    command: foreman-maintain service restart
    args:
      chdir: /root
      creates: /root/fog-testing/restart_services
    no_log: True
    changed_when: True

  - name: Wait 60 seconds for services to be fully up
    wait_for: timeout=60
    delegate_to: localhost

  - name: Upgrade Katello/Foreman to latest
    yum:
       name: '*'
       state: latest
    when: update_foreman|bool

  - name: Run upgrade hook since Katello/Foreman upgraded
    command: foreman-installer --upgrade -v -s --disable-system-checks
    args:
      chdir: /root
      creates: /root/fog-testing/upgrade
    when: update_foreman|bool
    register: installer_run

  - name: Generate new API cache data
    command: foreman-rake apipie:cache:index
    args:
      chdir: /root
      creates: /root/fog-testing/apicache_regen
    no_log: True
    changed_when: True

  - name: Check and make sure services are up
    command: hammer ping
    args:
      chdir: /root
      creates: /root/fog-testing/ping_check
    register: hping
    failed_when: hping.rc == 1

  - name: Start regression testing defined in create-hosts.yml
    block:
      - import_tasks: create-hosts.yml
    rescue:
      - debug:
          msg: An error occurred during the testing,rolling back to snapshot.
        when: is_debug is defined|bool
      - import_tasks: remove-hosts.yml
        static: yes

  - name: Delete VMS before reverting snapshot to prevent name taken error
    import_tasks: remove-hosts.yml
    static: yes

  - name: Revert VM back to "Fresh_Install" snapshot
    vmware_guest_snapshot:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      datacenter: "{{ vcenter_datacenter }}"
      folder: "{{ vcenter_folder }}"
      name: "{{ vcenter_vm_name }}"
      state: revert
      snapshot_name: "{{ vcenter_snapshot_name }}"
      validate_certs: no
    delegate_to: localhost
    when: revert_vm|bool

  - name: Poweroff Foreman Nightly VM
    vmware_guest_powerstate:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      folder: "/{{ vcenter_datacenter }}/{{ vcenter_folder }}"
      name: "{{ vcenter_vm_name }}"
      state: powered-off
    delegate_to: localhost