---

  - name: Revert VM to Upgrade snapshot
    vmware_guest_snapshot:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      datacenter: "{{ vcenter_datacenter }}"
      folder: "{{ vcenter_folder }}"
      name: "{{ vcenter_vm_name }}"
      state: revert
      snapshot_name: "{{ vcenter_snapshot_name }}"
      validate_certs: no
    delegate_to: localhost
    when: sat_upgrade|bool

  - name: Wait two minutes for VM to recover from snapshot restore
    wait_for: timeout=120
    delegate_to: localhost

  - name: Ping host to make sure it is responding
    ping: 
    when: sat_upgrade|bool
    delegate_to: localhost

  - name: Put Satellite SELinux into permissive
    selinux:
      policy: targeted
      state: permissive
    when: sat_upgrade|bool

  - name: Upgrade Red Hat Satellite to latest
    yum:
       name: '*'
       state: latest
    when: sat_upgrade|bool

  - name: Run upgrade hook since Red Hat Satellite upgraded
    command: satellite-installer --upgrade -v -s --disable-system-checks
    args:
      chdir: /root
      creates: /root/fog-testing/upgrade
    when: sat_upgrade|bool
    register: installer_run

  - name: Restart Red Hat Satellite services
    command: foreman-maintain service restart
    args:
      chdir: /root
      creates: /root/fog-testing/restart_services
    no_log: True
    changed_when: True

  - name: Wait 60 seconds for services to be fully up
    wait_for: timeout=60
    delegate_to: localhost

  - name: Generate new API cache data
    command: foreman-rake apipie:cache:index
    args:
      chdir: /root
      creates: /root/fog-testing/apicache_regen
    no_log: True
    changed_when: True

  - name: Check and make sure services are up
    command: hammer ping
    args:
      chdir: /root
      creates: /root/fog-testing/ping_check
    register: hping
    failed_when: hping.rc == 1
