---

  - name: Revert VM to "Upgrade" snapshot
    vmware_guest_snapshot:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      datacenter: "{{ vcenter_datacenter }}"
      folder: "{{ vcenter_folder }}"
      name: "{{ vcenter_vm_name }}"
      state: revert
      snapshot_name: "{{ vcenter_snapshot_name }}"
      validate_certs: no
    delegate_to: localhost
    when: update_foreman|bool

  - name: Wait two minutes for VM to recover from snapshot restore
    wait_for: timeout=120
    delegate_to: localhost

  - name: Ping host to make sure it is responding
    ping: 
    when: update_foreman|bool
    delegate_to: localhost

  - name: Put Foreman SELinux into permissive
    selinux:
      policy: targeted
      state: permissive
    when: update_foreman|bool

  - name: Upgrade Katello/Foreman to latest
    yum:
       name: '*'
       state: latest
    when: update_foreman|bool

  - name: Run upgrade hook since Katello/Foreman upgraded
    command: foreman-installer --upgrade -v -s --disable-system-checks
    args:
      chdir: /root
      creates: /root/fog-testing/upgrade
    when: update_foreman|bool
    register: installer_run

  - name: Restart Katello/Foreman services
    command: foreman-maintain service restart
    args:
      chdir: /root
      creates: /root/fog-testing/restart_services
    no_log: True
    changed_when: True

  - name: Wait 60 seconds for services to be fully up
    wait_for: timeout=60
    delegate_to: localhost

  - name: Generate new API cache data
    command: foreman-rake apipie:cache:index
    args:
      chdir: /root
      creates: /root/fog-testing/apicache_regen
    no_log: True
    changed_when: True

  - name: Check and make sure services are up
    command: hammer ping
    args:
      chdir: /root
      creates: /root/fog-testing/ping_check
    register: hping
    failed_when: hping.rc == 1